### ISSUE TITLE
nglview showing nothing after applying fix for  'AttributeError on import'

### ISSUE THREAD

**Issue by dgattiwsu** [nglviewer/nglview#1035]
Dear All, thank you in advance for your help on this issue.

I downgraded the  ipywidgets as recommended to fix the problem "AttributeError on import", issuing the following: 

conda install "ipywidgets <8" -c conda-forge

Now the import of nglview does not give an error any longer inside a Jupyter notebook, but calling nglview does not produce any output inside the notebook.

I am working remotely on the Wayne State University High Perfomance Computing grid, and unfortunately we are only allowed to invoke a Jupyter notebook rather than a Jupyter lab. The version of the notebook is established by the grid, not us. The following is a screenshot of the notebook. All cells were executed, but there was no output in the cells calling nglview.

![Screen Shot 2022-09-21 at 12 32 22 PM](https://user-images.githubusercontent.com/32550835/191560653-eb67332f-e2e5-4961-839e-190b50ddfec7.png)

**Comment by scottwsides** [comment]
Is this the error you're talking about (on 'import nglview') ?

AttributeError: 'super' object has no attribute '_ipython_display_

This just started happening recently for me and is breaking all my critical code. Is there a workaround ?

**Comment by dgattiwsu** [comment]
Yes, many times. Also the university grid at the end of the assigned time closes every session and removes anything that was not saved.

**Comment by dgattiwsu** [comment]
Just tried again with a brand new connection to the grid with the following lines:

![Screen Shot 2022-09-23 at 2 07 46 PM](https://user-images.githubusercontent.com/32550835/192030282-d58cd4bb-465d-4f04-a00e-6ccd19516635.png)

nglview seems to be importing everything correctly but does not show anything

﻿

**Comment by hainm** [comment]
Dear @dgattiwsu 

In this thread, @scottwsides found that v7.6 does not work but v7.7 does. And your ipywidgets version is 7.6.5
https://github.com/nglviewer/nglview/issues/1032#issuecomment-1254118207

Per the comment, I believe `ipywidgets=7.7.1 ` should work. 

<img width="941" alt="image" src="https://user-images.githubusercontent.com/4451957/192043291-2862899d-25ce-4ec3-86e5-e47b35a6a926.png">

**Comment by scottwsides** [comment]
Updating ipywidgets from 7.6.0 to 7.7.1 fixed my issues around nglview (and ipywidgets) throwing javascript errors

**Comment by dgattiwsu** [comment]
After updating ipywidgets to 7.7.1 still no errors but also no output:

![Screen Shot 2022-09-23 at 4 38 47 PM](https://user-images.githubusercontent.com/32550835/192053058-152120db-505e-4fd4-8506-ca790ba23ca8.png)

We are working to get jupyterlab running on our grid. Perhaps that will fix the problem

**Comment by dgattiwsu** [comment]
WORKS with jupyter lab!

![Screen Shot 2022-09-23 at 4 52 19 PM](https://user-images.githubusercontent.com/32550835/192054732-1db9d070-be55-45e8-b495-bb70c590baff.png)

So, somehow the problem is only limited to the notebook.

**Comment by hainm** [comment]
@dgattiwsu Nice. I think @scottwsides used jupyterlab too. 
But I am glad that works for you. cheers.

**Comment by MiloszGrabski** [comment]
> WORKS with jupyter lab!
> 
> ![Screen Shot 2022-09-23 at 4 52 19 PM](https://user-images.githubusercontent.com/32550835/192054732-1db9d070-be55-45e8-b495-bb70c590baff.png)
> 
> So, somehow the problem is only limited to the notebook.

Did it work for anybody else?
I have tried moving to 7.7.1, but still same issue in Jupyter Lab 3.5.0
![image](https://user-images.githubusercontent.com/69632186/201103219-cca7d0a1-7015-4624-999f-2513ad46daf5.png)
![image](https://user-images.githubusercontent.com/69632186/201103330-5896972b-8e30-4cd6-b9ae-b446dd1073a3.png)

**Comment by matteoferla** [comment]
I did the downgrade to `ipywidgets=7.7.1` after doing some searches into the whole `DOMWidget._ipython_display_` debacle (they basically broke every widget out there, e.g. plotly, by dropping this attribute).
But then errors mentioned above! This fixes if one refreshes the browser. 😆

**Comment by MiloszGrabski** [comment]
What do you mean by refreshes the browser, just literally, run the code first and then just hit F5?

**Comment by hainm** [comment]
That's right. Another way is to relaunch the notebook.
